%FS; FileSystem routine
	Q

READFILE(FILEPATH)
	N (FILEPATH)
	OPEN FILEPATH:(READONLY):5
	IF '$TEST WRITE "Could not open file",! QUIT

	S CONTENT=FILEPATH

	USE FILEPATH
	FOR  QUIT:$ZEOF  DO
	.READ LINE
	.S CONTENT($I(ROW))=LINE
	CLOSE FILEPATH

	S *RET=CONTENT Q *RET
