Test
	N

	W !!!

	S *FILE=$$READFILE^%FS("files/package.yaml")

	S BLOCKLEVEL=0

	S ROW=$NA(FILE) FOR  S ROW=$Q(@ROW) Q:(ROW="")  DO
	.S NR=$QS(ROW,1)
	.S LINE=@ROW
	.S KEY=$P(LINE,":",1)
	.S VALUE=$$L^%TRIM($P(LINE,":",2))
	.IF $A(VALUE)'=-1 S YAML(KEY)=VALUE
	.ELSE  DO
	..W "HEJ",!

	ZWR YAML

	;W $$L^%TRIM(" HEJSAN")

	Q

BLOCKLEVEL(ROW)
	N (ROW)
	S INDENT=$CHAR(32,32),COUNT=0
	S FIND="" FOR  S FIND=$FIND(ROW,INDENT,FIND) Q:(FIND=0)  S COUNT=$I(COUNT)
	Q COUNT


ISNEWBLOCK(LINE)
	Q $A($E(LINE,1))=32


;.IF $E($RE(VALUE))=":" W "END OF BLOCK:"_VALUE,!
;.W "["_LINE_"] "_VALUE,!4444x
;DSDSdddsa1321
;;;;DSDSADSADAS

CLEAR U $P:(X=0:Y=0:CLEAR) Q



